const STORAGE_KEY='dispatcherCommandCenter.v1';
const emptyState={xp:0,streak:1,shift:false,missions:[],trucks:[],loads:[],issues:[],cases:[],learning:[],journal:[]};
let state=loadState();
const $=id=>document.getElementById(id);
const money=n=>'$'+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0});
function loadState(){try{return {...emptyState,...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return {...emptyState}}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));updateStats()}
function addXP(n){state.xp=Math.max(0,state.xp+n);save()}
function setTab(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active-panel',p.id===id))}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));
$('shiftBtn').addEventListener('click',()=>{state.shift=!state.shift;save();renderShift()});
function renderShift(){$('shiftBtn').textContent=state.shift?'🔴 End Shift':'🟢 Start Shift';$('shiftState').textContent=state.shift?'🟢 Live Shift':'⚪ Off Shift'}
function updateStats(){const activeLoads=state.loads.filter(l=>l.status!=='Delivered').length,gross=state.loads.reduce((a,l)=>a+l.rate,0),openIssues=state.issues.filter(i=>!i.solved).length,totalMiles=state.loads.reduce((a,l)=>a+l.miles,0);$('xpTop').textContent=state.xp;$('streak').textContent=state.streak;$('statTrucks').textContent=state.trucks.length;$('statLoads').textContent=activeLoads;$('statGross').textContent=money(gross);$('statIssues').textContent=openIssues;$('missionDone').textContent=state.missions.filter(m=>m.done).length;$('missionTotal').textContent=state.missions.length;$('reviewXp').textContent=state.xp;$('reviewLoads').textContent=state.loads.length;$('reviewGross').textContent=money(gross);$('reviewRpm').textContent=totalMiles?'$'+(gross/totalMiles).toFixed(2):'$0.00';$('reviewCases').textContent=state.cases.length;$('reviewLearning').textContent=state.learning.length;$('reviewSolved').textContent=state.issues.filter(i=>i.solved).length;renderAttention()}
function empty(box,text){box.innerHTML=`<div class="item meta">${text}</div>`}
function renderMissions(){const box=$('missionList');box.innerHTML='';if(!state.missions.length)return empty(box,'No missions yet. Add 3–6 important goals for today.');state.missions.forEach((m,i)=>{const el=document.createElement('div');el.className='item item-row';el.innerHTML=`<label style="display:flex;align-items:center;gap:10px;margin:0;flex:1;color:inherit"><input type="checkbox" style="width:auto" ${m.done?'checked':''}><span ${m.done?'style="text-decoration:line-through;opacity:.6"':''}>${escapeHtml(m.text)}</span></label><button class="small-btn">🗑️</button>`;el.querySelector('input').addEventListener('change',e=>{m.done=e.target.checked;addXP(e.target.checked?10:-10);renderMissions()});el.querySelector('button').addEventListener('click',()=>{if(m.done)state.xp=Math.max(0,state.xp-10);state.missions.splice(i,1);save();renderMissions()});box.appendChild(el)})}
$('missionForm').addEventListener('submit',e=>{e.preventDefault();const text=$('missionText').value.trim();if(!text)return;state.missions.push({text,done:false});$('missionText').value='';save();renderMissions()});
function renderTrucks(){const box=$('truckList');box.innerHTML='';if(!state.trucks.length)return empty(box,'🚚 No trucks added yet.');state.trucks.forEach((t,i)=>{const el=document.createElement('article');el.className='card';el.innerHTML=`<div class="item-row"><div><b>🚛 Truck ${escapeHtml(t.no)}</b><div class="meta">${escapeHtml(t.driver)} · ${escapeHtml(t.equipment)}</div><div class="meta">📍 ${escapeHtml(t.loc||'Location not set')}</div></div><button class="small-btn">Remove</button></div>`;el.querySelector('button').addEventListener('click',()=>{state.trucks.splice(i,1);save();renderTrucks()});box.appendChild(el)})}
$('truckForm').addEventListener('submit',e=>{e.preventDefault();state.trucks.push({no:$('truckNo').value.trim(),driver:$('driverName').value.trim(),equipment:$('equipment').value,loc:$('truckLoc').value.trim()});e.target.reset();addXP(5);renderTrucks()});
function renderLoads(){const box=$('loadList');box.innerHTML='';if(!state.loads.length)return empty(box,'📦 No loads recorded yet.');state.loads.forEach((l,i)=>{const el=document.createElement('div');el.className='item';el.innerHTML=`<div class="item-row"><div><b>📦 Truck ${escapeHtml(l.truck)} · ${escapeHtml(l.origin)} → ${escapeHtml(l.destination)}</b><div class="meta">${escapeHtml(l.broker)} · ${escapeHtml(l.source)} · ${money(l.rate)}${l.miles?' · '+l.miles+' mi · $'+(l.rate/l.miles).toFixed(2)+'/mi':''}</div></div><select class="status" style="width:auto"><option>Booked</option><option>At Pickup</option><option>In Transit</option><option>At Delivery</option><option>Delivered</option></select></div><div style="margin-top:10px"><button class="small-btn remove">Remove</button></div>`;const sel=el.querySelector('.status');sel.value=l.status;sel.addEventListener('change',()=>{if(sel.value==='Delivered'&&l.status!=='Delivered')state.xp+=20;l.status=sel.value;save();renderLoads()});el.querySelector('.remove').addEventListener('click',()=>{state.loads.splice(i,1);save();renderLoads()});box.appendChild(el)})}
$('loadForm').addEventListener('submit',e=>{e.preventDefault();state.loads.push({truck:$('loadTruck').value.trim(),broker:$('loadBroker').value.trim(),rate:Number($('loadRate').value||0),origin:$('origin').value.trim(),destination:$('destination').value.trim(),miles:Number($('miles').value||0),status:$('loadStatus').value,source:$('source').value});e.target.reset();addXP(10);renderLoads()});
function renderIssues(){const box=$('issueList');box.innerHTML='';if(!state.issues.length)return empty(box,'✅ No issues recorded.');state.issues.forEach((x,i)=>{const el=document.createElement('div');el.className='item';el.innerHTML=`<div class="item-row"><div><b>${x.solved?'✅':'🚨'} ${escapeHtml(x.title)}</b><div class="meta">${escapeHtml(x.type)} · ${escapeHtml(x.priority)}</div><div class="meta">${escapeHtml(x.details||'No details')}</div></div><div><button class="small-btn toggle">${x.solved?'↩️ Reopen':'✅ Resolve'}</button> <button class="small-btn remove">Remove</button></div></div>`;el.querySelector('.toggle').addEventListener('click',()=>{x.solved=!x.solved;state.xp=Math.max(0,state.xp+(x.solved?20:-20));save();renderIssues()});el.querySelector('.remove').addEventListener('click',()=>{state.issues.splice(i,1);save();renderIssues()});box.appendChild(el)})}
$('issueForm').addEventListener('submit',e=>{e.preventDefault();state.issues.push({title:$('issueTitle').value.trim(),type:$('issueType').value,priority:$('issuePriority').value,details:$('issueDetails').value.trim(),solved:false});e.target.reset();save();renderIssues()});
function renderCases(filter=''){const box=$('caseList'),q=filter.toLowerCase();box.innerHTML='';const list=state.cases.filter(c=>`${c.problem} ${c.category} ${c.solution} ${c.lesson}`.toLowerCase().includes(q));if(!list.length)return empty(box,'🧠 No matching cases yet.');list.forEach(c=>{const el=document.createElement('div');el.className='item';el.innerHTML=`<b>🧩 ${escapeHtml(c.problem)}</b><div class="meta">${escapeHtml(c.category||'General')}</div><p><b>✅ Solution:</b> ${escapeHtml(c.solution)}</p><p><b>💡 Next time:</b> ${escapeHtml(c.lesson||'No prevention note')}</p>`;box.appendChild(el)})}
$('caseForm').addEventListener('submit',e=>{e.preventDefault();state.cases.unshift({problem:$('caseProblem').value.trim(),category:$('caseCategory').value.trim(),solution:$('caseSolution').value.trim(),lesson:$('caseLesson').value.trim()});e.target.reset();addXP(25);renderCases($('caseSearch').value)});$('caseSearch').addEventListener('input',e=>renderCases(e.target.value));
function renderLearning(){const box=$('learningList');box.innerHTML='';if(!state.learning.length)return empty(box,'🎓 No learning entries yet.');state.learning.forEach(l=>{const el=document.createElement('div');el.className='item';el.innerHTML=`<b>🎓 ${escapeHtml(l.topic)}</b><div class="meta">${escapeHtml(l.source||'Personal learning')}</div><p>📘 ${escapeHtml(l.note)}</p><p>${l.question?'❓ '+escapeHtml(l.question):'✅ No open question recorded.'}</p>`;box.appendChild(el)})}
$('learningForm').addEventListener('submit',e=>{e.preventDefault();state.learning.unshift({topic:$('learnTopic').value.trim(),source:$('learnSource').value.trim(),note:$('learnNote').value.trim(),question:$('learnQuestion').value.trim()});e.target.reset();addXP(15);renderLearning()});
function renderAttention(){const box=$('attentionBoard');box.innerHTML='';const open=state.issues.filter(i=>!i.solved).length;const activeLoads=state.loads.filter(l=>l.status!=='Delivered').length;const trucksToCover=Math.max(0,state.trucks.length-activeLoads);[['🚨 Open Problems',open,'Resolve critical issues first.'],['🚚 Trucks To Cover',trucksToCover,'Keep equipment moving.'],['🎓 Knowledge Entries',state.cases.length+state.learning.length,'Build your personal playbook.']].forEach(([title,noteCount,text])=>{const el=document.createElement('div');el.className='item';el.innerHTML=`<b>${title}: ${noteCount}</b><div class="meta">${text}</div>`;box.appendChild(el)})}
$('finishBtn').addEventListener('click',()=>{const total=state.missions.length,done=state.missions.filter(m=>m.done).length;const missionRate=total?done/total:0;let score=Math.round(45*missionRate+20*Math.min(1,state.loads.length/3)+15*Math.min(1,state.issues.filter(i=>i.solved).length/2)+20*Math.min(1,(state.cases.length+state.learning.length)/2));const grade=score>=90?'S':score>=80?'A':score>=70?'B':score>=60?'C':score>=45?'D':'F';state.journal.unshift({date:new Date().toISOString(),win:$('dayWin').value.trim(),mistake:$('dayMistake').value.trim(),improve:$('dayImprove').value.trim(),score,grade});state.xp+=grade==='S'?40:grade==='A'?30:grade==='B'?20:10;save();$('gradeBox').textContent=`🏆 Daily Grade: ${grade} · ${score}/100. Missions ${done}/${total}. ${grade==='S'||grade==='A'?'Excellent operational discipline.':grade==='B'?'Solid day. Keep improving documentation and completion rate.':'Review unfinished work and set one clear improvement for tomorrow.'}`});
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
renderShift();renderMissions();renderTrucks();renderLoads();renderIssues();renderCases();renderLearning();updateStats();
